const BASE_URL = 'http://qtest.fareed9.com:8081';
const CUSTOMER_SERVICE = 'service-qetaa-customer';
const LOCATION_SERVICE = 'service-qetaa-location';
const VEHICLE_SERVICE = 'service-qetaa-vehicle';
const CART_SERVICE = 'service-qetaa-cart';
const PRODUCT_SERVICE = 'service-qetaa-product';
const API_VERSION = '/rest/api/v1';
const EMAIL_LOGIN_URL = `${CUSTOMER_SERVICE}${API_VERSION}/login/email`;
const SIGNUP_URL = `${CUSTOMER_SERVICE}${API_VERSION}/signup`;
const ADD_ADDRESS_URL = `${CUSTOMER_SERVICE}${API_VERSION}/address`;
const ADD_VEHICLE_URL = `${CUSTOMER_SERVICE}${API_VERSION}/vehicle`;
const SOCIAL_MEDIA_LOGIN_URL = `${CUSTOMER_SERVICE}${API_VERSION}/login/social-media`;
const SOCIAL_MEDIA_LINK_URL = `${CUSTOMER_SERVICE}${API_VERSION}/social-media`;
const EMAIL_REGISTER_URL = `${CUSTOMER_SERVICE}${API_VERSION}/register/email`;
const SOCIAL_MEDIA_REGISTER_URL = `${CUSTOMER_SERVICE}${API_VERSION}/register/social-media`;
const RESET_PASSWORD_URL = `${CUSTOMER_SERVICE}${API_VERSION}/reset-password`;
const RESET_SMS_URL = `${CUSTOMER_SERVICE}${API_VERSION}/reset-sms/mobile`;
const CHANGE_NAME_URL = `${CUSTOMER_SERVICE}${API_VERSION}/customer`;
const CHANGE_EMAIL_URL = `${CUSTOMER_SERVICE}${API_VERSION}/change-email`;
const CHANGE_PASSWORD_URL = `${CUSTOMER_SERVICE}${API_VERSION}/password`;
const FIND_CITY_URL = `${LOCATION_SERVICE}${API_VERSION}/find-city`;
const COUNTRIES_URL = `${LOCATION_SERVICE}${API_VERSION}/countries`;
const REGIONS_URL = `${LOCATION_SERVICE}${API_VERSION}/regions/country-id`;
const GET_MAKES_URL = `${VEHICLE_SERVICE}${API_VERSION}/makes`;
const GET_QUOTATION_CART_URL = `${CART_SERVICE}${API_VERSION}/quotation-carts/customer`;
const ADD_QUOTATION_CART_URL = `${CART_SERVICE}${API_VERSION}/quotation-cart`;
const GET_PRODUCTS_BEST_SELLERS = `${PRODUCT_SERVICE}${API_VERSION}/best-sellers`;
const GET_PRODUCTS_OFFERS = `${PRODUCT_SERVICE}${API_VERSION}/offers`;

module.exports = {
 BASE_URL,
 EMAIL_LOGIN_URL,
 SIGNUP_URL,
 EMAIL_REGISTER_URL,
 SOCIAL_MEDIA_REGISTER_URL,
 COUNTRIES_URL,
 REGIONS_URL,
 FIND_CITY_URL,
 SOCIAL_MEDIA_LOGIN_URL,
 RESET_PASSWORD_URL,
 RESET_SMS_URL,
 SOCIAL_MEDIA_LINK_URL,
 ADD_ADDRESS_URL,
 ADD_VEHICLE_URL,
 GET_MAKES_URL,
 CHANGE_EMAIL_URL,
 CHANGE_PASSWORD_URL,
 CHANGE_NAME_URL,
 GET_QUOTATION_CART_URL,
 ADD_QUOTATION_CART_URL,
 GET_PRODUCTS_BEST_SELLERS,
 GET_PRODUCTS_OFFERS
}